services:
  # The Locust engine is used for load testing purposes.
  locust-brain:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/home/locust/locustfile.py
      - ./requirements.txt:/home/locust/requirements.txt
      - ./baseECR/LA:/home/locust/baseECR/LA
    command: -f /home/locust/locustfile.py --master -H $LOAD_TESTING_URL
  locust-worker-1:
    image: locustio/locust
    volumes:
      - ./locustfile.py:/home/locust/locustfile.py
      - ./requirements.txt:/home/locust/requirements.txt
      - ./baseECR/LA:/home/locust/baseECR/LA
    command: -f /home/locust/locustfile.py --worker --master-host locust-brain
  locust-worker-2:
    image: locustio/locust
    volumes:
      - ./locustfile.py:/home/locust/locustfile.py
      - ./requirements.txt:/home/locust/requirements.txt
      - ./baseECR/LA:/home/locust/baseECR/LA
    command: -f /home/locust/locustfile.py --worker --master-host locust-brain
  locust-worker-3:
    image: locustio/locust
    volumes:
      - ./locustfile.py:/home/locust/locustfile.py
      - ./requirements.txt:/home/locust/requirements.txt
      - ./baseECR/LA:/home/locust/baseECR/LA
    command: -f /home/locust/locustfile.py --worker --master-host locust-brain
