name: ecr-viewer

include:
  - ../docker-compose.yaml
services:
  fhir-converter-service:
    platform: linux/amd64
    build:
      context: ../../fhir-converter/
    ports:
      - "8082:8080"

  ingestion-service:
    platform: linux/amd64
    build:
      context: ../../ingestion
    ports:
      - "8083:8080"
    logging:
      driver: "json-file"
    environment:
      SMARTY_AUTH_ID: ${SMARTY_AUTH_ID}
      SMARTY_AUTH_TOKEN: ${SMARTY_AUTH_TOKEN}

  message-parser-service:
    platform: linux/amd64
    build:
      context: ../../message-parser
    ports:
      - "8085:8080"
    logging:
      driver: "json-file"

  trigger-code-reference-service:
    platform: linux/amd64
    build:
      context: ../../trigger-code-reference
    ports:
      - "8086:8080"
    logging:
      driver: "json-file"

  orchestration-service:
    platform: linux/amd64
    build:
      context: ../../orchestration/
    depends_on:
      - fhir-converter-service
      - ingestion-service
      - message-parser-service
      - ecr-viewer
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
    env_file:
      - ../../orchestration/.env
    environment:
      - OTEL_TRACES_EXPORTER=none
      - OTEL_METRICS_EXPORTER=none
      - ECR_VIEWER_URL=http://ecr-viewer:3000/ecr-viewer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://orchestration-service:8080/"]
      interval: 10s
      timeout: 20s
      retries: 5

  convert-data:
    build: .
    depends_on:
      orchestration-service:
        condition: service_healthy
    ports:
      - "8081:8081"
    volumes:
      - ./baseECR:/code/baseECR
    environment:
      - CONFIG_NAME=${CONFIG_NAME}
      - SEED_DATA_DIRECTORIES=${SEED_DATA_DIRECTORIES:-LA}
